# Enable the Corne RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

# Enable automatic lighting timeout
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=60000
CONFIG_ZMK_IDLE_SLEEP=y

# Enable the Corne OLED display
CONFIG_ZMK_DISPLAY=y
