# Enable the Corne RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

# Enable automatic sleep after one minute of inactivity
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# Enable the Corne OLED display
CONFIG_ZMK_DISPLAY=y

# Keep the display on instead of blanking it after inactivity
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
